CREATE TABLE [dbo].[Contact]
(
    [Id] UNIQUEIDENTIFIER NOT NULL CONSTRAINT [DF_Contact_Id] DEFAULT NEWSEQUENTIALID(),
    [Email] NVARCHAR(255) NOT NULL,
    [Name] NVARCHAR(100) NOT NULL,
    [PhoneNumber] NVARCHAR(50) NULL,
    CONSTRAINT [PK_Contact] PRIMARY KEY CLUSTERED ([Id])
);